language: node_js
node_js:
- 4.2.3
deploy:
  skip_cleanup: true
  api_key:
    secure: q385CcraZYxkWRxFV3LUTKnGYUzB0ZQo6QL8g0vkAe2gZG/4zWp7zX6oxxmS/YyKrlyZgmZn5grs3T2yjtUBJo76PZUqnEx2CLIVujoEc77TCdY+EA/EsvFFbOdj7XFxaylBAjd2qvb5H7LVttp86Q0hd9QJVbyA06Cr3gEi5ok158AuWfa/gmgbrekGZiiUA/KJnq28DsqW5EQ0LpesJjQTLPojHiRfwNv0ckl71qn83/IDC747QenIYTC2tfQfVKbZZMlz5ICPrm1LTpeRSwu6Pk57tZb/EHzgaj3Afd+g1NjkWtz2eausSrRnEsFu7bSFVasm1Uv55cKSKC7MIdE+SjlU6Jj1Hh5T+kcLdVGPtygvac2EJfcy8GFuYAkzdjveG6rt1qpHWk/r/tX6xwrVTntfwvWOpX1klz839PfrE7ns8dGRKcLNGhycsBzxm311D/bsSPTvwF03i6BC6vJQMpTHJXktGshOcYhmVcP/KWDQ5b/ChJ0EqcwWCc8MoUpOiuZd+TbtLCGz/Cf3WFyZjMTVoSJpeZBiYy0D5/YFqtGVCJN2R02wUECPU9Thx+sT+9ITU4v1T/k0IQ37KnUHlT3vHaAYddm231BI76klFaYtUsjwSXDUOtscpnks9t01Jm8JIQVXRvtuiTyAqz9tGjinLRte/QjUbqvhMVQ=
